from __future__ import annotations

from dataclasses import asdict

from leopardi.finetune.config import (
    AdapterConfig,
    FinetuneLossWeights,
    FinetuneOptimizerConfig,
    FinetuneRuntimeConfig,
    FinetuneStageConfig,
    ModuleLrConfig,
    RewardWeights,
    SamplingConfig,
    SchedulerConfig,
    VerifierConfig,
)


def finetune_stage_recipe(stage: str) -> FinetuneStageConfig:
    runtime = FinetuneRuntimeConfig()

    recipes = {
        "f0_general_sft": FinetuneStageConfig(
            stage="f0_general_sft",
            visual_mode="standard",
            data_bundle_ids=("sft_core_v1", "f0_general_sft_v1"),
            adapter=AdapterConfig(mode="full", rank=0, alpha=0, dropout=0.0),
            optimizer=FinetuneOptimizerConfig(lr=1e-4, weight_decay=0.05),
            runtime=runtime,
            scheduler=SchedulerConfig(name="cosine", warmup_ratio=0.06, min_lr_ratio=0.15),
            sampling=SamplingConfig(
                easy_ratio=0.28,
                medium_ratio=0.34,
                hard_ratio=0.28,
                pathological_ratio=0.10,
                failure_replay_ratio=0.10,
                refresh_failure_buffer_every=500,
                keep_clean_anchor_fraction=0.18,
            ),
            module_lr=ModuleLrConfig(
                visual_tokenizer=0.45,
                latent_bottleneck=0.75,
                planner=1.05,
                writer=1.2,
                auxiliary_heads=1.0,
            ),
            verifier=VerifierConfig(
                reward_clip=2.0,
                normalize_rewards=True,
                min_reward_group_size=8,
                informative_reward_floor=0.02,
                target_latency_ms=1250.0,
                target_output_tokens=4096,
                kl_anchor_beta=0.0,
            ),
            loss_weights=FinetuneLossWeights(
                token_ce=1.0,
                formula_ce=0.10,
                table_ce=0.10,
                repair_ce=0.0,
                block_type=0.15,
                block_length=0.05,
                specialist_hint=0.08,
                block_box=0.05,
                rotation=0.03,
                handwriting=0.03,
                formula_tokens=0.08,
                table_blocks=0.08,
                table_spans=0.04,
                reward_anchor=0.0,
                kl_anchor=0.0,
                label_smoothing=0.02,
            ),
            reward_weights=RewardWeights(),
        ),
        "f1_specialist_sft": FinetuneStageConfig(
            stage="f1_specialist_sft",
            visual_mode="hard",
            data_bundle_ids=("sft_core_v1", "f1_specialist_sft_v1"),
            adapter=AdapterConfig(mode="full", rank=0, alpha=0, dropout=0.0),
            optimizer=FinetuneOptimizerConfig(lr=8e-5, weight_decay=0.05),
            runtime=runtime,
            scheduler=SchedulerConfig(name="cosine", warmup_ratio=0.04, min_lr_ratio=0.18),
            sampling=SamplingConfig(
                easy_ratio=0.14,
                medium_ratio=0.24,
                hard_ratio=0.40,
                pathological_ratio=0.22,
                failure_replay_ratio=0.22,
                refresh_failure_buffer_every=250,
                keep_clean_anchor_fraction=0.18,
            ),
            module_lr=ModuleLrConfig(
                visual_tokenizer=0.55,
                latent_bottleneck=0.85,
                planner=1.15,
                writer=1.25,
                auxiliary_heads=1.05,
            ),
            verifier=VerifierConfig(
                reward_clip=2.2,
                normalize_rewards=True,
                min_reward_group_size=6,
                informative_reward_floor=0.015,
                target_latency_ms=1350.0,
                target_output_tokens=5120,
                kl_anchor_beta=0.0,
            ),
            loss_weights=FinetuneLossWeights(
                token_ce=1.0,
                formula_ce=0.22,
                table_ce=0.22,
                repair_ce=0.18,
                block_type=0.2,
                block_length=0.05,
                specialist_hint=0.14,
                block_box=0.08,
                rotation=0.10,
                handwriting=0.10,
                formula_tokens=0.18,
                table_blocks=0.18,
                table_spans=0.10,
                reward_anchor=0.0,
                kl_anchor=0.0,
                label_smoothing=0.01,
            ),
            reward_weights=RewardWeights(
                markdown_validity=1.05,
                latex_validity=0.9,
                table_validity=0.9,
                formula_exactness=0.9,
                header_footer_suppression=0.5,
                chart_text=0.3,
            ),
        ),
        "f2_repair_sft": FinetuneStageConfig(
            stage="f2_repair_sft",
            track="s0-repair",
            visual_mode="hard",
            data_bundle_ids=("sft_repair_v1", "f2_repair_sft_v1"),
            adapter=AdapterConfig(mode="full", rank=0, alpha=0, dropout=0.0),
            optimizer=FinetuneOptimizerConfig(lr=6e-5, weight_decay=0.03),
            runtime=runtime,
            scheduler=SchedulerConfig(name="cosine", warmup_ratio=0.03, min_lr_ratio=0.2),
            sampling=SamplingConfig(
                easy_ratio=0.08,
                medium_ratio=0.18,
                hard_ratio=0.40,
                pathological_ratio=0.34,
                failure_replay_ratio=0.35,
                refresh_failure_buffer_every=200,
                keep_clean_anchor_fraction=0.08,
            ),
            module_lr=ModuleLrConfig(
                visual_tokenizer=0.40,
                latent_bottleneck=0.75,
                planner=1.1,
                writer=1.3,
                auxiliary_heads=1.0,
            ),
            verifier=VerifierConfig(
                reward_clip=2.3,
                normalize_rewards=True,
                min_reward_group_size=6,
                informative_reward_floor=0.01,
                target_latency_ms=1450.0,
                target_output_tokens=3584,
                kl_anchor_beta=0.01,
            ),
            loss_weights=FinetuneLossWeights(
                token_ce=0.6,
                formula_ce=0.12,
                table_ce=0.12,
                repair_ce=1.0,
                block_type=0.1,
                block_length=0.05,
                specialist_hint=0.1,
                block_box=0.03,
                rotation=0.02,
                handwriting=0.02,
                formula_tokens=0.08,
                table_blocks=0.1,
                table_spans=0.05,
                reward_anchor=0.1,
                kl_anchor=0.02,
                label_smoothing=0.01,
            ),
            reward_weights=RewardWeights(
                markdown_validity=1.2,
                latex_validity=1.0,
                table_validity=1.0,
                reading_order=0.5,
                edit_similarity=1.2,
                formula_exactness=1.0,
                header_footer_suppression=0.6,
                output_length_penalty=0.08,
                latency_penalty=0.2,
                repair_budget_penalty=0.15,
            ),
        ),
        "f3_rlvr": FinetuneStageConfig(
            stage="f3_rlvr",
            visual_mode="hard",
            adapter=AdapterConfig(
                mode="lora",
                rank=32,
                alpha=64,
                dropout=0.05,
                target_modules=("writer", "planner", "latent_bottleneck"),
            ),
            optimizer=FinetuneOptimizerConfig(lr=5e-5, weight_decay=0.0),
            runtime=FinetuneRuntimeConfig(
                hardware_tag="rtx5090",
                precision="bf16",
                compile_model=False,
                gradient_checkpointing=True,
                micro_batch_size=1,
                gradient_accumulation_steps=8,
                dataloader_workers=2,
                max_steps=3000,
                log_every=10,
                eval_every=100,
                save_every=100,
            ),
            scheduler=SchedulerConfig(name="cosine", warmup_ratio=0.02, min_lr_ratio=0.3),
            sampling=SamplingConfig(
                easy_ratio=0.06,
                medium_ratio=0.16,
                hard_ratio=0.42,
                pathological_ratio=0.36,
                failure_replay_ratio=0.40,
                refresh_failure_buffer_every=100,
                keep_clean_anchor_fraction=0.06,
            ),
            module_lr=ModuleLrConfig(
                visual_tokenizer=0.0,
                latent_bottleneck=0.85,
                planner=1.1,
                writer=1.15,
                auxiliary_heads=0.75,
            ),
            verifier=VerifierConfig(
                reward_clip=2.5,
                normalize_rewards=True,
                min_reward_group_size=4,
                informative_reward_floor=0.01,
                target_latency_ms=1200.0,
                target_output_tokens=3072,
                kl_anchor_beta=0.02,
            ),
            loss_weights=FinetuneLossWeights(
                token_ce=0.4,
                formula_ce=0.08,
                table_ce=0.08,
                repair_ce=0.3,
                block_type=0.05,
                block_length=0.02,
                specialist_hint=0.05,
                block_box=0.02,
                rotation=0.0,
                handwriting=0.0,
                formula_tokens=0.03,
                table_blocks=0.03,
                table_spans=0.02,
                reward_anchor=1.0,
                kl_anchor=0.05,
                label_smoothing=0.0,
            ),
            reward_weights=RewardWeights(
                markdown_validity=1.2,
                latex_validity=1.0,
                table_validity=1.0,
                reading_order=0.5,
                edit_similarity=1.2,
                formula_exactness=1.0,
                header_footer_suppression=0.6,
                chart_text=0.4,
                output_length_penalty=0.1,
                latency_penalty=0.25,
                repair_budget_penalty=0.2,
            ),
        ),
    }
    if stage not in recipes:
        raise KeyError(f"Unknown finetune stage recipe: {stage}")
    return recipes[stage]


def finetune_stage_recipe_dict(stage: str) -> dict[str, object]:
    return asdict(finetune_stage_recipe(stage))
